name: 'Lint Markdown & Frontmatter'
description: 'GitHub Action linting markdown &amp; its frontmatter content.'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'Steve'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'dist/index.js'
